samples:
    - E7.5_sample_1
    - E6.5_sample_4
    - E7.5_sample_2
    - E6.5_sample_5
    - E6.5_sample_2
    - E6.5_sample_3
    - E7.5_sample_4
    - E7.5_sample_3
    - E5.5_sample_1
    - E4.5_sample_2
    - E5.5_sample_2
    - E4.5_sample_1
    - E7.5_sample_10
    - E7.5_sample_12
    - E7.5_sample_11
    - E7.5_sample_13
    - E7.5_sample_14
    - E7.5_sample_15
    - E7.5_sample_5
    - E6.5_sample_6
    - E6.5_sample_12
    - E3.5_sample_1
    - TET_experiment_E8.5_WT_CD41+
    - TET_experiment_E8.5_WT_KDR+
    - TET_experiment_E8.5_WT_KDR+_CD41+
    - TET_experiment_E8.5_WT

genomic_contexts:
    - multiome_peaks
    - CGI
    - H3K27ac_distal_E7.5_Ect_intersect12
    - H3K27ac_distal_E7.5_End_intersect12
    - H3K27ac_distal_E7.5_Mes_intersect12
    - LINE
    - LTR
    - genebody
    - prom_2000_2000
    - prom_2000_2000_cgi
    - prom_2000_2000_noncgi
    - prom_200_200
    - prom_200_200_cgi
    - prom_200_200_noncgi

stages: ["E3.5","E4.5","E5.5","E6.5","E7.5","E8.5"]
# celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]

#################
## Directories ##
#################

directories:
    base: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019
    processed_data: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/processed
    results: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/results
    features: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/features/genomic_contexts
    genome_seq: /bi/group/reik/ricard/data/mm10_sequence/mm10.genome
    bedGraphToBigWig: "/bi/apps/ucsc_tools/5/bedGraphToBigWig"
    rna_SingleCellExperiment: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/processed/rna/SingleCellExperiment.rds
    cell_metadata: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/results/rna/celltype_assignment/sample_metadata_after_celltype_rename.txt.gz # this is the output of the RNA snakemake pipeline
    tss_file: /bi/group/reik/ricard/data/mm10_regulation/genes/TSS_protein_coding.bed

#############
## Scripts ##
#############

scripts:
    calculate_global_stats_per_cell: ../stats/calculate_stats.R
    calculate_chr_stats_per_cell: ../stats/calculate_stats_per_chr.R
    plot_global_stats_per_cell: ../stats/plot_stats.R
    plot_chr_stats_per_cell: ../stats/plot_stats_per_chr.R
    qc: ../qc/qc.R
    parse_metadata_after_qc: ../qc/parse_sample_metadata_after_qc.R
    quantify_feature_level: ../quantify_feature_level/quantify_feature_level.R
    pseudobulk: ../pseudobulk/pseudobulk_metacc.R
    boxplots_metacc_feature_level: ../boxplots_feature_level/boxplots_feature_level.R
    calculate_tss_profiles: ../profiles/calculate_metacc_profiles.R
    plot_tss_profiles: ../profiles/plot_metacc_profiles.R
    bigwig: ../bigwig/create_bigwig_pseudobulk.R
    metrna_coupling: ../../metrna/coupling/local_coupling/calculate_metrna_coupling.R
    metacc_coupling: ../../metacc/coupling/local_coupling/calculate_metacc_coupling.R
    accrna_coupling: ../../accrna/coupling/local_coupling/calculate_accrna_coupling.R



################
## Parameters ##
################

params:
    qc_met:
        minimum_number_sites: 5000
        min_rate: 0
        max_rate: 100
    qc_acc:
        minimum_number_sites: 10000
        min_rate: 10
        max_rate: 40
    pseudobulk:
        group_by: ["stage"]
        # group_by: ["celltype", "celltype2", "celltype3"]
        min_cells: 10
    calculate_tss_profiles:
        window_size: 3000
        met_tile: 100
        acc_tile: 50
    calculate_profiles_multiome_peaks:
        window_size: 2000
        met_tile: 200
        acc_tile: 100
    bigwig_met:
        step_size: 500
        min_rate_bigwig: 10
    bigwig_acc:
        step_size: 100
        min_rate_bigwig: 5
    metrna_coupling:
        up: 3000
        down: 3000
        window: 150
        tile: 50
    metacc_coupling:
        up: 3000
        down: 3000
        window: 150
        tile: 50
    accrna_coupling:
        up: 3000
        down: 3000
        window: 100
        tile: 50

###########
## Slurm ##
###########

slurm:  # memory in MB
    calculate_global_stats_per_cell: 
        memory: 15000
        threads: 1
    calculate_chr_stats_per_cell: 
        memory: 35000
        threads: 1
    plot_global_stats_per_cell: 
        memory: 3000
        threads: 1
    qc: 
        memory: 5000
        threads: 1
    quantify_met_feature_level: 
        memory: 20000
        threads: 1
    quantify_acc_feature_level: 
        memory: 40000
        threads: 1
    pseudobulk: 
        memory: 25000
        threads: 1
    boxplots_metacc_feature_level: 
        memory: 5000
        threads: 1
    calculate_tss_profiles: 
        memory: 90000
        threads: 1
    calculate_profiles_multiome_peaks: 
        memory: 130000
        threads: 1
    plot_tss_profiles: 
        memory: 10000
        threads: 1    
    bigwig_met:
        memory: 25000
        threads: 1    
    bigwig_acc:
        memory: 60000
        threads: 1    
    metrna_coupling:
        memory: 10000
        threads: 1   
    accrna_coupling:
        memory: 15000
        threads: 1   
    metacc_coupling:
        memory: 15000
        threads: 1   
